### ISSUE TITLE
S60P not able to flash original bootloader

### ISSUE THREAD

**Issue by discip** [Ralim/IronOS-dfu#24]
Unfortunately I was not able to flash the original bootloader obeying the following instruction: https://github.com/Ralim/IronOS-dfu/blob/mainline/docs/BackUp.md#restoring-your-bootloader

**Comment by discip** [comment]
@Ralim
Unfortunately not only what I mentioned above is true but also if the IronOS bootloader is flashed there are no possibilities to flash anything, as no matter which button you hold during boot, even if it boots without a button pressed it always boots to the bootloader (Which by the way shows scrambled pixels left and right besides the text.).

**Comment by damex** [comment]
> @Ralim Unfortunately not only what I mentioned above is true but also if the IronOS bootloader is flashed there are no possibilities to flash anything, as no matter which button you hold during boot, even if it boots without a button pressed it always boots to the bootloader (Which by the way shows scrambled pixels left and right besides the text.).

how did you flash ironos bootloader? i bricked mine after flashing runtime bootloader and would like to recover or atleast get it to run current ironos-dfu in current state

i just tried on mine and it does not get detected by stlink after connecting DIO/CLK/GND and either powering iron from stlink or from usb port. i tried shorting boot0 or holding reset to no avail. holding boot0 on s60 worked just fine and it got detected by stlink but not s60p

**Comment by damex** [comment]
> > @Ralim Unfortunately not only what I mentioned above is true but also if the IronOS bootloader is flashed there are no possibilities to flash anything, as no matter which button you hold during boot, even if it boots without a button pressed it always boots to the bootloader (Which by the way shows scrambled pixels left and right besides the text.).
> 
> how did you flash ironos bootloader? i bricked mine after flashing runtime bootloader and would like to recover or atleast get it to run current ironos-dfu in current state
> 
> i just tried on mine and it does not get detected by stlink after connecting DIO/CLK/GND and either powering iron from stlink or from usb port. i tried shorting boot0 or holding reset to no avail. holding boot0 on s60 worked just fine and it got detected by stlink but not s60p

turns out i need to HOLD shorted RST and then use try to unlock flash by using this:
`
sudo openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg -c 'init; reset halt; stm32f1x unlock 0; reset halt; exit'
`
and error like
`
Warn : UNEXPECTED idcode: 0x2ba01477
Error: expected 1 of 1: 0x1ba01477
`
fixed by replacing id of 0x1ba01477 by 0x2ba01477 in  /usr/share/openocd/scripts/target/stm32f1x.cfg since we have a cloned chip in there. maybe there is better way to do so?

then it bootloader could be flashed as

`
sudo st-flash --connect-under-reset --format=ihex write ~/Downloads/S60P/bootloader.hex                                     
st-flash 1.7.0
2024-04-05T03:12:38 WARN common.c: NRST is not connected
2024-04-05T03:12:38 INFO common.c: F1xx Medium-density: 20 KiB SRAM, 128 KiB flash in at least 1 KiB pages.
2024-04-05T03:12:38 INFO common.c: Attempting to write 5380 (0x1504) bytes to stm32 address: 134217728 (0x8000000)
2024-04-05T03:12:38 INFO common.c: Flash page at addr: 0x08000000 erased
2024-04-05T03:12:38 INFO common.c: Flash page at addr: 0x08000400 erased
2024-04-05T03:12:38 INFO common.c: Flash page at addr: 0x08000800 erased
2024-04-05T03:12:38 INFO common.c: Flash page at addr: 0x08000c00 erased
2024-04-05T03:12:38 INFO common.c: Flash page at addr: 0x08001000 erased
2024-04-05T03:12:38 INFO common.c: Flash page at addr: 0x08001400 erased
2024-04-05T03:12:38 INFO common.c: Finished erasing 6 pages of 1024 (0x400) bytes
2024-04-05T03:12:38 INFO common.c: Starting Flash write for VL/F0/F3/F1_XL
2024-04-05T03:12:38 INFO flash_loader.c: Successfully loaded flash loader in sram
2024-04-05T03:12:38 INFO flash_loader.c: Clear DFSR
  6/  6 pages written
2024-04-05T03:12:38 INFO common.c: Starting verification of write complete
2024-04-05T03:12:38 INFO common.c: Flash written and verified! jolly good!
`

so in the end i got working ironos-dfu bootloader. i think you can flash original this way if you have a backup

**Comment by discip** [comment]
You were faster. I was just trying to remember how I did that. 😅

> so in the end i got working ironos-dfu bootloader. i think you can flash original this way if you have a backup

So, you managed to flash the IronOS bootloader directly?
If so could you please apply the necessary changes as a PR to IronOS-dfu?

**Comment by damex** [comment]
> You were faster. I was just trying to remember how I did that. 😅
> 
> > so in the end i got working ironos-dfu bootloader. i think you can flash original this way if you have a backup
> 
> So, you managed to flash the IronOS bootloader directly? If so could you please apply the necessary changes as a PR to IronOS-dfu?

if i understand you correctly - nope, you can not flash ironos bootloader without using swd/stlink dongle.

if one tries to overwrite bootloader portion or write in other forbidden zones (not sure which ones) - protection comes up and flash gets zeroed out. only way out is to remove write lock (protection bit) either using st-link software or openocd (this part need SWD/STLINK connection to iron) and then flash bootloader using stlink software/stm32cubeprogrammer/stlink-tools or anything else that writes to stm32 over swd  (still needs SWD/STLINK connection to iron)

in the log that shown above - i remove write lock/protection bit using openocd and then flash bootloader using st-flash.

**Comment by discip** [comment]
## Solved by #26!
